// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/chatStream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatStream_Chat_FullMethodName = "/chatStream.ChatStream/Chat"
)

// ChatStreamClient is the client API for ChatStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatStreamClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error)
}

type chatStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewChatStreamClient(cc grpc.ClientConnInterface) ChatStreamClient {
	return &chatStreamClient{cc}
}

func (c *chatStreamClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatStream_ServiceDesc.Streams[0], ChatStream_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, ChatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatStream_ChatClient = grpc.BidiStreamingClient[ChatMessage, ChatMessage]

// ChatStreamServer is the server API for ChatStream service.
// All implementations must embed UnimplementedChatStreamServer
// for forward compatibility.
type ChatStreamServer interface {
	Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error
	mustEmbedUnimplementedChatStreamServer()
}

// UnimplementedChatStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatStreamServer struct{}

func (UnimplementedChatStreamServer) Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatStreamServer) mustEmbedUnimplementedChatStreamServer() {}
func (UnimplementedChatStreamServer) testEmbeddedByValue()                    {}

// UnsafeChatStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatStreamServer will
// result in compilation errors.
type UnsafeChatStreamServer interface {
	mustEmbedUnimplementedChatStreamServer()
}

func RegisterChatStreamServer(s grpc.ServiceRegistrar, srv ChatStreamServer) {
	// If the following call pancis, it indicates UnimplementedChatStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatStream_ServiceDesc, srv)
}

func _ChatStream_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatStreamServer).Chat(&grpc.GenericServerStream[ChatMessage, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatStream_ChatServer = grpc.BidiStreamingServer[ChatMessage, ChatMessage]

// ChatStream_ServiceDesc is the grpc.ServiceDesc for ChatStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatStream.ChatStream",
	HandlerType: (*ChatStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _ChatStream_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/chatStream.proto",
}
